wikidataintegrator/wdi_core.py

When sparql_query come from WDBaseDataType.

Escape single quote in __select_wd_item

---

wikibaseintegrator/tests/test_all.py
wikibaseintegrator/tests/test_backoff.py

Change to httpbin.org (#38)

---

wikibaseintegrator/tests/test_fastrun.py
wikibaseintegrator/wbi_core.py
wikibaseintegrator/wbi_fastrun.py

Rework the query to query data for the fastrun.
Thanks to User:Dipsacus_fullonum for the help.

Rework fastrun query data

---

wikibaseintegrator/tests/test_all.py
wikibaseintegrator/tests/test_fastrun.py
wikibaseintegrator/tests/test_wd_search.py
wikibaseintegrator/wbi_backoff.py
wikibaseintegrator/wbi_core.py
wikibaseintegrator/wbi_fastrun.py

From WikidataIntegrator
Update related usage
Format files
Co-Authored-By: andrawaag <770306+andrawaag@users.noreply.github.com>

Add FunctionsEngine in wbi_core

---

wikibaseintegrator/tests/test_item_creation.py
wikibaseintegrator/wbi_core.py

Direct support BaseDataType for data parameter of wbi_core.ItemEngine

---

README.md

Add references example in README.md

---

wikibaseintegrator/tests/test_wd_search.py
wikibaseintegrator/wbi_core.py

From upstream https://github.com/SuLab/WikidataIntegrator/pull/167
+ add parameter search_type
Co-Authored-By: Noah Finberg <8573212+NoahFinberg@users.noreply.github.com>

get_search_results: Optionally return additional info + add search type

---

wikibaseintegrator/wbi_core.py

Add more checks if value is None

---

test/test_wdi_login.py
wikibaseintegrator/wbi_core.py

Raise an exception if mediawiki_api_url mismatch

---

wikibaseintegrator/wbi_core.py

Correctly remove MappingRelationHelper

---

wikibaseintegrator/wbi_core.py

Remove maxlag parameter if maxlag is 0 or less and add maxlag to more functions.

Change maxlag

---

README.md
wikibaseintegrator/wbi_config.py
wikibaseintegrator/wbi_login.py

Add OAuth 2.0 support

---

wikibaseintegrator/wbi_core.py

Quick fix for int issue

---

README.md
test/test_all.py
wikibaseintegrator/__init__.py
wikibaseintegrator/wbi_config.py
wikibaseintegrator/wbi_helpers.py
wikibaseintegrator/wbi_login.py

Allow the operator to specify a string that will be prepend to the User-Agent.
Improve #181

Improve useragent

---

test/test_all.py
test/test_wbi_core.py
test/test_wbi_fastrun.py
wikibaseintegrator/datatypes/basedatatype.py
wikibaseintegrator/entities/baseentity.py
wikibaseintegrator/models/aliases.py
wikibaseintegrator/models/claims.py
wikibaseintegrator/models/language_values.py
wikibaseintegrator/models/qualifiers.py
wikibaseintegrator/models/references.py
wikibaseintegrator/models/senses.py
wikibaseintegrator/models/snaks.py
wikibaseintegrator/wbi_enums.py
wikibaseintegrator/wbi_fastrun.py
wikibaseintegrator/wikibaseintegrator.py

New file wbi_enums.py with 3 new enums: ActionIfExists, WikibaseSnakValueType, WikibaseRank
Replace all string arguments with the new enums.
I did not update all the comments in the type classes.
If you like this, I'll clean up the comments. :)
All 17 tests = OK

Implement enums 

---

wikibaseintegrator/wbi_datatype.py

Add the keyword "now" to Time datatype to set the value to the current UTC time
Close #210

Add the keyword "now" to Time datatype to set the value to the current UTC time

---

test/test_wbi_helpers.py
wikibaseintegrator/wbi_helpers.py

Add retry for HTTP Code 500, 502 and 504

---

.idea/WikibaseIntegrator.iml

Exclude folder "wikibaseintegrator.egg-info"

Update PyCharm files

---

requirements.txt
setup.cfg
setup.py
test/test_all.py
test/test_entity_item.py
test/test_wbi_fastrun.py
wikibaseintegrator/datatypes/basedatatype.py
wikibaseintegrator/datatypes/commonsmedia.py
wikibaseintegrator/datatypes/form.py
wikibaseintegrator/datatypes/geoshape.py
wikibaseintegrator/datatypes/globecoordinate.py
wikibaseintegrator/datatypes/item.py
wikibaseintegrator/datatypes/lexeme.py
wikibaseintegrator/datatypes/monolingualtext.py
wikibaseintegrator/datatypes/property.py
wikibaseintegrator/datatypes/quantity.py
wikibaseintegrator/datatypes/sense.py
wikibaseintegrator/datatypes/string.py
wikibaseintegrator/datatypes/tabulardata.py
wikibaseintegrator/datatypes/time.py
wikibaseintegrator/datatypes/url.py
wikibaseintegrator/entities/baseentity.py
wikibaseintegrator/models/claims.py
wikibaseintegrator/wbi_fastrun.py

* base_filter use a list of BaseDataType
* Add a set_value() function in BaseDataType classes
* Fix multiple _get_sparql_value()
* Comment fr_search()

Rework FastRun for using WBI DataModel

---

README.md
notebooks/item_create_new.ipynb
notebooks/lexeme_update.ipynb
notebooks/lexeme_write.ipynb
test/test_wbi_backoff.py
test/test_wbi_login.py
wikibaseintegrator/wbi_login.py

Separate each auth method in a class.

Rewrite wbi_login

---

wikibaseintegrator/datatypes/time.py

Add value in ValueError message

---

wikibaseintegrator/entities/baseentity.py
wikibaseintegrator/wbi_helpers.py

Add delete page support (#312)

---

wikibaseintegrator/entities/baseentity.py

fix #325
the code is untested, might be space/tab issues

Fix missing attributes in MW 1.35

---

test/test_entity_item.py
wikibaseintegrator/entities/baseentity.py
wikibaseintegrator/wbi_exceptions.py
wikibaseintegrator/wbi_helpers.py

Co-Authored-By: Dennis Priskorn <dennis@priskorn.se>

Add NonExistentEntityError exception

---

README.md

README.md: Fix the readability of readability

---

wikibaseintegrator/wbi_fastrun.py
wikibaseintegrator/wbi_login.py

https://pypi.org/project/flynt

Convert to Python f-strings with flynt

---

test/test_wbi_exceptions.py
wikibaseintegrator/wbi_exceptions.py

Reintroduce getting the conflicting entity id and the language

---

wikibaseintegrator/models/claims.py

State the default in the docstring

Improve claims.add() docstring

---

test/test_wbi_exceptions.py
wikibaseintegrator/wbi_exceptions.py

Allow missing informations inside the error_dict.
Close #395

Improve MWApiError

---

test/test_wbi_exceptions.py

Co-Authored-By: Dennis Priskorn <dennis@priskorn.se>

Add test_invalid_claim

---

wikibaseintegrator/wbi_exceptions.py
wikibaseintegrator/wbi_helpers.py

* Add an attribute with the error dictionnary
* Fix MWApiError call

Improve/Fix Exceptions

---

notebooks/import_entity.ipynb
wikibaseintegrator/entities/baseentity.py

Allow to write an entity as a new one

---

wikibaseintegrator/entities/baseentity.py
wikibaseintegrator/wbi_helpers.py

Replace baseentity._write() with a call to wbi_helpers.edit_entity()

Add wbi_helpers.edit_entity()

---

wikibaseintegrator/wbi_helpers.py

Add:
* lexeme_add_form
* lexeme_edit_form
* lexeme_remove_form
* lexeme_add_sense
* lexeme_edit_sense
* lexeme_remove_sense

Add lexeme helpers

---

test/test_wbi_core.py
wikibaseintegrator/datatypes/item.py
wikibaseintegrator/datatypes/lexeme.py
wikibaseintegrator/datatypes/property.py
wikibaseintegrator/wbi_helpers.py

For Item/Property/Lexeme
Closes #503
Closes #505

Add concept URI as value

---

wikibaseintegrator/models/claims.py
wikibaseintegrator/models/forms.py
wikibaseintegrator/models/language_values.py
wikibaseintegrator/models/senses.py
wikibaseintegrator/models/sitelinks.py

Generalize __len__() support

---

test/test_entity_item.py
test/test_entity_lexeme.py
test/test_entity_mediainfo.py
test/test_entity_property.py
wikibaseintegrator/entities/baseentity.py
wikibaseintegrator/entities/item.py
wikibaseintegrator/entities/lexeme.py
wikibaseintegrator/entities/mediainfo.py
wikibaseintegrator/entities/property.py

Add get_entity_url()

---

test/test_entity_item.py
wikibaseintegrator/datatypes/monolingualtext.py
wikibaseintegrator/datatypes/musicalnotation.py
wikibaseintegrator/datatypes/string.py

Add newline test for String and MonolingualText

---

test/test_wbi_core.py
wikibaseintegrator/models/claims.py

Add Claim.reset_id() method

---

README.md

Close #588 
Close #586 
Close #585 
Close #584 
Close #583 
Close #582 
Close #581 
Close #578 
Close #577 
Close #574

More example projects added

---

wikibaseintegrator/models/claims.py
wikibaseintegrator/wbi_enums.py

@LeMyst I've redone this changes in this other fork, should be better to read! Sorry for the mess!

Add ActionIfExists.MERGE_REFS_OR_APPEND (#607)

---

README.md

add get lemma on lexeme
I have not tested this.

Add get lemma example to README.md

---

pyproject.toml

Bump package version from 0.12.13.dev0 to 0.12.13 for official release.

Release version 0.12.13

---

pyproject.toml

Update the development version to 0.12.15.dev0 to prepare for upcoming changes.

Bump version to 0.12.15.dev0 in pyproject.toml
